### ISSUE TITLE
No route matches [GET]

### ISSUE THREAD

**Issue by mwalimu82** [jgraichen/redmine_dashboard#115]
```
ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_dashboard/javascripts/jquery.ui.js"):
  actionpack (4.1.13) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.13) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.13) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  actionpack (4.1.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.13) lib/rails/engine.rb:514:in `call'
  railties (4.1.13) lib/rails/application.rb:144:in `call'
  railties (4.1.13) lib/rails/railtie.rb:194:in `public_send'
  railties (4.1.13) lib/rails/railtie.rb:194:in `method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

**Comment by bar-souza** [comment]
I have this problem too in redmine 3.1

**Comment by jgraichen** [comment]
Please try running `rake redmine:plugins:assets` to copy the plugin assets. Usually this is done by redmine somewhere...

**Comment by mwalimu82** [comment]
I solved it.
rake did not work for me. The solution was to add into

/etc/apache2/sites-enabled/001-redmine.conf

this:

Alias "/plugin_assets/" /var/cache/redmine/default/plugin_assets/
<Directory "/var/cache/redmine/default/plugin_assets">
    Allow from all
    Options -MultiViews
    Require all granted
</Directory>
