### ISSUE TITLE
Missing minitest require?

### ISSUE THREAD

**Issue by adamos42** [jgraichen/redmine_dashboard#128]
My console output when I want to migrate the plugin into my Redmine 3.3:
```
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
  /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
  /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
  /usr/local/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
  /usr/local/lib/ruby/2.1.0/test/unit.rb:1:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `require'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `rescue in block in require'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:68:in `block in require'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
  /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
  /srv/redmine-3.3.0-development/config/application.rb:8:in `<top (required)>'
  /srv/redmine-3.3.0-development/Rakefile:5:in `require'
  /srv/redmine-3.3.0-development/Rakefile:5:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load'
  /usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load_rakefile'
  /usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:686:in `raw_load_rakefile'
  /usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:96:in `block in load_rakefile'
  /usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
  /usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:95:in `load_rakefile'
  /usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:79:in `block in run'
  /usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
  /usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
  /usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
  /usr/local/bin/rake:23:in `load'
  /usr/local/bin/rake:23:in `<main>'
MiniTest::Unit::TestCase is now Minitest::Test. From /usr/local/lib/ruby/2.1.0/test/unit/testcase.rb:8:in `<module:Unit>'
rake aborted!
NameError: undefined method `_run_suite' for class `Test::Unit::Runner'
/usr/local/lib/ruby/2.1.0/test/unit.rb:676:in `<class:Runner>'
/usr/local/lib/ruby/2.1.0/test/unit.rb:261:in `<module:Unit>'
/usr/local/lib/ruby/2.1.0/test/unit.rb:15:in `<module:Test>'
/usr/local/lib/ruby/2.1.0/test/unit.rb:7:in `<top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `rescue in block in require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:68:in `block in require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/srv/redmine-3.3.0-development/config/application.rb:8:in `<top (required)>'
/srv/redmine-3.3.0-development/Rakefile:5:in `require'
/srv/redmine-3.3.0-development/Rakefile:5:in `<top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:686:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:95:in `load_rakefile'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:79:in `block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
LoadError: cannot load such file -- test-unit
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/srv/redmine-3.3.0-development/config/application.rb:8:in `<top (required)>'
/srv/redmine-3.3.0-development/Rakefile:5:in `require'
/srv/redmine-3.3.0-development/Rakefile:5:in `<top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:686:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:95:in `load_rakefile'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:79:in `block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

My Gems:
```
Gems included by the bundle:
  * actionmailer (4.2.6)
  * actionpack (4.2.6)
  * actionpack-action_caching (1.1.1)
  * actionpack-xml_parser (1.0.2)
  * actionview (4.2.6)
  * activejob (4.2.6)
  * activemodel (4.2.6)
  * activerecord (4.2.6)
  * activesupport (4.2.6)
  * acts-as-taggable-on (3.5.0)
  * addressable (2.5.0)
  * arel (6.0.3)
  * awesome_nested_set (3.1.1)
  * builder (3.2.2)
  * bundler (1.11.2)
  * chartkick (2.1.1)
  * coderay (1.1.1)
  * colorize (0.8.1)
  * concurrent-ruby (1.0.2)
  * content_for_in_controllers (0.0.2)
  * css_parser (1.4.6)
  * deface (1.0.2)
  * docx (0.2.07)
  * erubis (2.7.0)
  * globalid (0.3.7)
  * groupdate (3.1.1)
  * htmlentities (4.3.1)
  * i18n (0.7.0)
  * icalendar (1.5.3)
  * jquery-rails (3.1.4)
  * json (1.8.3)
  * loofah (2.0.3)
  * mail (2.6.4)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * mimemagic (0.3.2)
  * mini_portile2 (2.1.0)
  * minitest (5.9.1)
  * mysql2 (0.3.21)
  * net-ldap (0.12.1)
  * nokogiri (1.6.8.1)
  * polyglot (0.3.5)
  * premailer (1.8.7)
  * premailer-rails (1.9.4)
  * protected_attributes (1.1.3)
  * prototype-rails (4.0.0 0fed929)
  * public_suffix (2.0.4)
  * rack (1.6.5)
  * rack-openid (1.4.2)
  * rack-test (0.6.3)
  * rails (4.2.6)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.7)
  * rails-html-sanitizer (1.0.3)
  * rails_sql_views (0.8.2.undev 5792b63)
  * railties (4.2.6)
  * rake (11.3.0)
  * rbpdf (1.19.0)
  * rbpdf-font (1.19.0)
  * redcarpet (3.3.4)
  * redmine_acts_as_taggable_on (1.1.0 a939bae)
  * render_parent (0.0.8)
  * request_store (1.0.5)
  * rmagick (2.16.0)
  * roadie (3.2.0)
  * roadie-rails (1.1.1)
  * ruby-openid (2.3.0)
  * rubyzip (1.1.7)
  * rufus-scheduler (3.2.2)
  * slim (3.0.7)
  * sprockets (3.7.0)
  * sprockets-rails (3.2.0)
  * temple (0.7.7)
  * thor (0.18.1)
  * thread_safe (0.3.5)
  * tilt (2.0.5)
  * tzinfo (1.2.2)
  * write_xlsx (0.83.0)
  * ya2yaml (0.31)
  * zip-zip (0.3)
```

**Comment by jgraichen** [comment]
Did you set `RAILS_ENV` and passed some `--without`s to the bundle and rake command?

**Comment by adamos42** [comment]
Yes and no.

I used this command after I cloned the plugin into the **plugins** directory:
`bundle exec rake redmine:plugins:migrate RAILS_ENV=production`

**Comment by jgraichen** [comment]
Please try `bundle install --without development test`.

It's probably some test dependency of Redmine or the plugins gems that is tried to get loaded by the Rakefile. The plugin itself does not use `mini-test` et al.
