### ISSUE TITLE
not compatible redmine 4.0

### ISSUE THREAD

**Issue by mattttv** [jgraichen/redmine_dashboard#138]
hello!
thanks for the plugin!
i have the current tagged stable version 2.7.1 installed and was able to go through all the bundle-update and migrate-scripts that are necessary to update redmine from 3.4 to 4.0 if installed from svn - but opening up the 4.0 site results in a non-working website and following lines inside apache-log: [1]

can you please help me on this?

Kind Regards,
Matt

```
[ 2019-01-28 15:41:34.6531 31888/7fe8016cc700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn proc
ess for application /var/www/redmine/redmine-current/: An error occurred while starting up the preloader
.                                                 
  Error ID: 4b984617                                                                                    
  Error details saved to: /tmp/passenger-error-b8uMHu.html                                              
  Message from application: undefined method `before_filter' for RdbDashboardController:Class
Did you mean?  before_action (NoMethodError)                                                        
  /var/www/redmine/redmine-4.0/plugins/redmine_dashboard/app/controllers/rdb_dashboard_controller.rb:4:i
n `<class:RdbDashboardController>'                                 
  /var/www/redmine/redmine-4.0/plugins/redmine_dashboard/app/controllers/rdb_dashboard_controller.rb:1:i
n `<top (required)>'                                                        
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in requi
re'                                                                               
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependenc
y'                                                                                      
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'      
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:378:in `block in requi
re_or_load'                                                                               
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `block in load_i
nterlock'                                                                                               
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:14:in `block
 in loading'                                                                                 
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:151:in `excl
usive'                                                                                         
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:13:in `loadi
ng'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:37:in `load_interlock'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:356:in `require_or_loa
d'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:334:in `depend_on'
  /var/lib/gems/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:246:in `require_depend
ency'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:477:in `each'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:477:in `block in eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:475:in `each'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:475:in `eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/engine.rb:356:in `eager_load!'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:69:in `each'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/application/finisher.rb:69:in `block in <module:Fini
sher>'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
  /var/lib/gems/2.3.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
  /var/www/redmine/redmine-current/config/environment.rb:14:in `<top (required)>'
  /var/www/redmine/redmine-current/config.ru:3:in `require'
  /var/www/redmine/redmine-current/config.ru:3:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
  /var/www/redmine/redmine-current/config.ru:1:in `new'
  /var/www/redmine/redmine-current/config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'


[ 2019-01-28 15:41:34.6589 31888/7fe7fb016700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-2] Cannot
 checkout session because a spawning error occurred. The identifier of the error is 4b984617. Please see
 earlier logs for details about the error.

**Comment by jgraichen** [comment]
Please try Redmine Dashboard from `stable-v2` branch. I added some patches there but do not have much time (nor a platform) for thorough testing. I will try to make a new release soon if it works for you too.
