### ISSUE TITLE
Filter Parent Task problem

### ISSUE THREAD

**Issue by KinGsNowGH** [jgraichen/redmine_dashboard#142]
When i try to use the 'Parent Task' Group Filter it just doesnt work at all, as i show you below:

Ubuntu 18.04
Docker redmine 4.1.0

terminal error:
172.16.100.2 - - [20/Feb/2020:16:08:34 UTC] "GET /projects/test/rdb/taskboard?group=parent&_=1582214089095 HTTP/1.
1" 500 648                                                                                                              
http://10.10.10.213:7001/projects/test/rdb/taskboard -> /projects/test/rdb/taskboard?group=parent&_=15822140
89095

Web interface:
Ajax Error: Internal Server Error

**Comment by jgraichen** [comment]
Please provide the serve log too otherwise I cannot help here.

**Comment by sdrstone1** [comment]
I have the same problem. and I got a server log.

Docker Redmine 4.1.0
CentOS 7 

server log: (my name and project name is replaced)

```
App 185 output: I, [2021-02-09T02:37:39.661855 #185]  INFO -- : Started GET "/projects/mbed-bp6a/rdb/taskboard?group=parent&_=1612838254001" for 192.168.7.42 at 2021-02-09 02:37:39 +0000
App 185 output: I, [2021-02-09T02:37:39.663538 #185]  INFO -- : Processing by RdbTaskboardController#index as JS
App 185 output: I, [2021-02-09T02:37:39.663656 #185]  INFO -- :   Parameters: {"group"=>"parent", "_"=>"1612838254001", "id"=>"{projectID}"}
App 185 output: I, [2021-02-09T02:37:39.675355 #185]  INFO -- :   Current user: {userName} (id=5)
App 185 output: I, [2021-02-09T02:37:39.691075 #185]  INFO -- : Completed 500 Internal Server Error in 27ms (ActiveRecord: 9.4ms)
App 185 output: F, [2021-02-09T02:37:39.691400 #185] FATAL -- :   
App 185 output: F, [2021-02-09T02:37:39.691775 #185] FATAL -- : NoMethodError (undefined method `all' for #<Array:0x00007fed5549e180>
App 185 output: Did you mean?  all?):
App 185 output: F, [2021-02-09T02:37:39.691792 #185] FATAL -- :   
App 185 output: F, [2021-02-09T02:37:39.691805 #185] FATAL -- : plugins/redmine_dashboard/app/models/rdb_taskboard.rb:76:in `build'
App 185 output: plugins/redmine_dashboard/app/controllers/rdb_dashboard_controller.rb:39:in `setup_board'
App 185 output: plugins/redmine_dashboard/app/controllers/rdb_dashboard_controller.rb:12:in `index'
App 185 output: lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```
