### ISSUE TITLE
zeitwerk issue, still

### ISSUE THREAD

**Issue by ungentilgarcon** [jgraichen/redmine_dashboard#244]
**Describe the bug**
install on docker redmine: bullseye

```
redminePROD | Exiting
redminePROD | /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file /usr/src/redmine/plugins/onlyoffice_redmine/app/models/file_uitility.rb to define constant FileUitility, but didn't (Zeitwerk::NameError)
redminePROD |
redminePROD |       raise Zeitwerk::NameError.new("expected file #{file} to define constant #{cpath}, but didn't", cref.last)
redminePROD |       ^^^^^
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:28:in `require'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
redminePROD |   from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
redminePROD |   from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
redminePROD |   from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
redminePROD |   from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
redminePROD |   from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
redminePROD |   from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
redminePROD |   from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
redminePROD |   from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
redminePROD |   from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
redminePROD |   from /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
redminePROD |   from /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
redminePROD |   from /usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
redminePROD |   from /usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
redminePROD |   from /usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
redminePROD |   from config.ru:3:in `block in <main>'
redminePROD |   from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
redminePROD |   from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
redminePROD |   from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
redminePROD |   from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
redminePROD |   from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
redminePROD |   from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
redminePROD |   from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
redminePROD |   from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/server.rb:312:in `block in start'
redminePROD |   from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/server.rb:379:in `handle_profiling'
redminePROD |   from /usr/local/bundle/gems/rack-2.2.3.1/lib/rack/server.rb:311:in `start'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:39:in `start'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:144:in `block in perform'
redminePROD |   from <internal:kernel>:90:in `tap'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:135:in `perform'
redminePROD |   from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
redminePROD |   from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
redminePROD |   from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/command/base.rb:69:in `perform'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/command.rb:48:in `invoke'
redminePROD |   from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands.rb:18:in `<top (required)>'
redminePROD |   from bin/rails:4:in `require'
```

**Comment by jgraichen** [comment]
Not an issue with this plugin:

```
redminePROD | /usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file /usr/src/redmine/plugins/onlyoffice_redmine/app/models/file_uitility.rb to define constant FileUitility, but didn't (Zeitwerk::NameError)
```

Please contact the `onlyoffice_redmine` plugin developers.

**Comment by ungentilgarcon** [comment]
indeed I just noticed it, thank you
