### ISSUE TITLE
Empty screen in Dashborad. Completed 500 Internal Server Error.

### ISSUE THREAD

**Issue by n0rvik** [jgraichen/redmine_dashboard#348]
**Describe the bug**
Error: Empty screen Redmine Dashboard.  Log file: Completed 500 Internal Server Error.

```
Completed 500 Internal Server Error in 198ms (ActiveRecord: 5.1ms)

ActionView::Template::Error (undefined method `haml_tag' for #<#<Class:0x00007f2e74c1ec48>:0x00007f2e75263e28>):
    1: .rdb-board
    2:   = link_to '', rdb_board_path, :class => "rdb-async", :id => "rdb-refresh"
    3:
    4:   - render_rdb_menu :board, @board.name, :header => :h2 do
    5:     - render_rdb_menu_list [:taskboard] do |val|
    6:       = link_to t("rdb_#{val}"), rdb_path(:board => val)
    7:
```

**To Reproduce**

1. Go to 'Dashboard'
2. See error

**Expected behavior**
Work screen Redmine Dashboard with work tables.

**Screenshots**

**Redmine**

```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Mercurial                      5.3
  Git                            2.9.5
  Filesystem                     
Redmine plugins:
  redmine_dashboard              2.10.0
  redmine_drawio                 1.4.6
  redmine_image_clipboard_paste  3.3.0
  redmine_tags                   4.0.0
  redmine_theme_changer          0.5.0
  redmine_tint_issues            1.3.2
  redmine_work_time              0.4.1

```

```
Started GET "/projects/proj011/rdb" for 192.168.65.176 at 2023-02-09 12:34:04 +0300
Processing by RdbDashboardController#index as HTML
  Parameters: {"id"=>"proj011"}
  Token Update All (1.1ms)  UPDATE "tokens" SET "updated_on" = '2023-02-09 12:34:04.821190' WHERE "tokens"."user_id" = $1 AND "tokens"."value" = $2 AND "tokens"."action" = $3  [["user_id", 1], ["value", "0c1df6e29fdbfd41ef72e9626e819536647c3b14"], ["action", "session"]]
   (0.4ms)  SELECT MAX("settings"."updated_on") FROM "settings"
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."type" IN ('User', 'AnonymousUser') AND "users"."status" = $1 AND "users"."id" = $2 LIMIT $3  [["status", 1], ["id", 1], ["LIMIT", 1]]
  Current user: admin (id=1)
  Project Load (0.3ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."identifier" = $1 LIMIT $2  [["identifier", "proj011"], ["LIMIT", 1]]
   (0.3ms)  SELECT "enabled_modules"."name" FROM "enabled_modules" WHERE "enabled_modules"."project_id" = $1  [["project_id", 19]]
Redirected to https://test-redmine.inforion.ru/projects/proj011/rdb/taskboard
  UserPreference Load (0.3ms)  SELECT  "user_preferences".* FROM "user_preferences" WHERE "user_preferences"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
Completed 302 Found in 13ms (ActiveRecord: 3.0ms)
Started GET "/projects/proj011/rdb/taskboard" for 192.168.65.176 at 2023-02-09 12:34:04 +0300
Processing by RdbTaskboardController#index as HTML
  Parameters: {"id"=>"proj011"}
  Token Update All (1.0ms)  UPDATE "tokens" SET "updated_on" = '2023-02-09 12:34:04.838180' WHERE "tokens"."user_id" = $1 AND "tokens"."value" = $2 AND "tokens"."action" = $3  [["user_id", 1], ["value", "0c1df6e29fdbfd41ef72e9626e819536647c3b14"], ["action", "session"]]
   (0.5ms)  SELECT MAX("settings"."updated_on") FROM "settings"
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."type" IN ('User', 'AnonymousUser') AND "users"."status" = $1 AND "users"."id" = $2 LIMIT $3  [["status", 1], ["id", 1], ["LIMIT", 1]]
  Current user: admin (id=1)
  Project Load (0.3ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."identifier" = $1 LIMIT $2  [["identifier", "proj011"], ["LIMIT", 1]]
   (0.3ms)  SELECT "enabled_modules"."name" FROM "enabled_modules" WHERE "enabled_modules"."project_id" = $1  [["project_id", 19]]
  Version Exists (0.5ms)  SELECT  1 AS one FROM "versions" WHERE "versions"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 1]]
  IssueCategory Exists (0.4ms)  SELECT  1 AS one FROM "issue_categories" WHERE "issue_categories"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 1]]
  IssueStatus Load (0.4ms)  SELECT "issue_statuses".* FROM "issue_statuses" ORDER BY "issue_statuses"."position" ASC
  Rendering plugins/redmine_dashboard/app/views/rdb_dashboard/index.html.haml within layouts/base
  IssuePriority Load (0.8ms)  SELECT "enumerations".* FROM "enumerations" WHERE "enumerations"."type" IN ('IssuePriority') ORDER BY "enumerations"."position" ASC
  Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/_footer.html.haml (24.2ms)
  Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/index.html.haml within layouts/base (45.6ms)
  ThemeChangerUserSetting Load (0.4ms)  SELECT  "theme_changer_user_settings".* FROM "theme_changer_user_settings" WHERE "theme_changer_user_settings"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
  UserPreference Load (0.3ms)  SELECT  "user_preferences".* FROM "user_preferences" WHERE "user_preferences"."user_id" = $1 LIMIT $2  [["user_id", 1], ["LIMIT", 1]]
  Rendered plugins/redmine_tint_issues/app/views/hooks/redmine_tint_issues/_tint_issues_css.html.erb (0.4ms)
  Rendered plugins/redmine_tags/app/views/tags/_header_assets.html.erb (0.3ms)
  Project Load (0.4ms)  SELECT "projects"."id", "projects"."name", "projects"."identifier", "projects"."lft", "projects"."rgt" FROM "projects" INNER JOIN "members" ON "projects"."id" = "members"."project_id" WHERE "members"."user_id" = $1 AND "projects"."status" != $2 AND "projects"."status" = $3  [["user_id", 1], ["status", 9], ["status", 1]]
  Project Load (0.5ms)  SELECT "projects".* FROM "projects" WHERE "projects"."id" = $1 AND (projects.status <> 9)  [["id", 1]]
  Project Load (0.5ms)  SELECT "projects".* FROM "projects" WHERE "projects"."id" IN ($1, $2, $3)  [["id", 19], ["id", 9], ["id", 20]]
  Tracker Exists (0.7ms)  SELECT  1 AS one FROM "trackers" INNER JOIN "projects_trackers" ON "trackers"."id" = "projects_trackers"."tracker_id" WHERE "projects_trackers"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 1]]
  CACHE Tracker Exists (0.0ms)  SELECT  1 AS one FROM "trackers" INNER JOIN "projects_trackers" ON "trackers"."id" = "projects_trackers"."tracker_id" WHERE "projects_trackers"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 1]]
  Version Exists (0.8ms)  SELECT  1 AS one FROM "versions" INNER JOIN "projects" ON "projects"."id" = "versions"."project_id" WHERE (projects.id = 19 OR (projects.status <> 9 AND ( versions.sharing = 'system' OR (projects.lft >= 15 AND projects.rgt <= 16 AND versions.sharing = 'tree') OR (projects.lft < 15 AND projects.rgt > 16 AND versions.sharing IN ('hierarchy', 'descendants')) OR (projects.lft > 15 AND projects.rgt < 16 AND versions.sharing = 'hierarchy')))) LIMIT $1  [["LIMIT", 1]]
  Wiki Load (0.4ms)  SELECT  "wikis".* FROM "wikis" WHERE "wikis"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 1]]
  Board Exists (0.4ms)  SELECT  1 AS one FROM "boards" WHERE "boards"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 1]]
  Repository Load (0.4ms)  SELECT  "repositories".* FROM "repositories" WHERE "repositories"."project_id" = $1 AND "repositories"."is_default" = $2 LIMIT $3  [["project_id", 19], ["is_default", true], ["LIMIT", 1]]
  Rendered plugins/redmine_drawio/app/views/redmine_drawio/_macro_dialog.html.erb (0.5ms)
Completed 200 OK in 106ms (Views: 74.7ms | ActiveRecord: 11.8ms)
Started GET "/projects/proj011/rdb/taskboard?&_=1675935245542" for 192.168.65.176 at 2023-02-09 12:34:05 +0300
Processing by RdbTaskboardController#index as JS
  Parameters: {"_"=>"1675935245542", "id"=>"proj011"}
  Token Update All (1.0ms)  UPDATE "tokens" SET "updated_on" = '2023-02-09 12:34:05.086833' WHERE "tokens"."user_id" = $1 AND "tokens"."value" = $2 AND "tokens"."action" = $3  [["user_id", 1], ["value", "0c1df6e29fdbfd41ef72e9626e819536647c3b14"], ["action", "session"]]
   (0.5ms)  SELECT MAX("settings"."updated_on") FROM "settings"
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."type" IN ('User', 'AnonymousUser') AND "users"."status" = $1 AND "users"."id" = $2 LIMIT $3  [["status", 1], ["id", 1], ["LIMIT", 1]]
  Current user: admin (id=1)
  Project Load (0.3ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."identifier" = $1 LIMIT $2  [["identifier", "proj011"], ["LIMIT", 1]]
   (0.3ms)  SELECT "enabled_modules"."name" FROM "enabled_modules" WHERE "enabled_modules"."project_id" = $1  [["project_id", 19]]
  Version Exists (0.4ms)  SELECT  1 AS one FROM "versions" WHERE "versions"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 1]]
  IssueCategory Exists (0.4ms)  SELECT  1 AS one FROM "issue_categories" WHERE "issue_categories"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 1]]
  IssueStatus Load (0.4ms)  SELECT "issue_statuses".* FROM "issue_statuses" ORDER BY "issue_statuses"."position" ASC
  Rendering plugins/redmine_dashboard/app/views/rdb_dashboard/index.js.erb
  Project Load (0.5ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = $1 ORDER BY "projects"."lft" ASC LIMIT $2  [["id", 19], ["LIMIT", 11]]
  Version Load (0.3ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 11]]
  IssueCategory Load (0.3ms)  SELECT  "issue_categories".* FROM "issue_categories" WHERE "issue_categories"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 11]]
  CACHE Project Load (0.0ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = $1 ORDER BY "projects"."lft" ASC LIMIT $2  [["id", 19], ["LIMIT", 11]]
  CACHE Version Load (0.0ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 11]]
  CACHE IssueCategory Load (0.0ms)  SELECT  "issue_categories".* FROM "issue_categories" WHERE "issue_categories"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 11]]
  CACHE Project Load (0.0ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = $1 ORDER BY "projects"."lft" ASC LIMIT $2  [["id", 19], ["LIMIT", 11]]
  CACHE Version Load (0.0ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 11]]
  CACHE IssueCategory Load (0.0ms)  SELECT  "issue_categories".* FROM "issue_categories" WHERE "issue_categories"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 11]]
  CACHE Project Load (0.0ms)  SELECT  "projects".* FROM "projects" WHERE "projects"."id" = $1 ORDER BY "projects"."lft" ASC LIMIT $2  [["id", 19], ["LIMIT", 11]]
  CACHE Version Load (0.0ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 11]]
  CACHE IssueCategory Load (0.0ms)  SELECT  "issue_categories".* FROM "issue_categories" WHERE "issue_categories"."project_id" = $1 LIMIT $2  [["project_id", 19], ["LIMIT", 11]]
  Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_header.html.haml (82.3ms)
  Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/_taskboard.html.haml (103.3ms)
  Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/index.js.erb (135.9ms)
Completed 500 Internal Server Error in 198ms (ActiveRecord: 5.1ms)

ActionView::Template::Error (undefined method `haml_tag' for #<#<Class:0x00007f2e74c1ec48>:0x00007f2e75263e28>):
    1: .rdb-board
    2:   = link_to '', rdb_board_path, :class => "rdb-async", :id => "rdb-refresh"
    3:
    4:   - render_rdb_menu :board, @board.name, :header => :h2 do
    5:     - render_rdb_menu_list [:taskboard] do |val|
    6:       = link_to t("rdb_#{val}"), rdb_path(:board => val)
    7:

plugins/redmine_dashboard/app/helpers/rdb_dashboard_helper.rb:9:in `render_rdb_menu'
plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_header.html.haml:4:in `_plugins_redmine_dashboard_app_views_rdb_dashboard_taskboard__header_html_haml___1968487633688565982_69918755807540'
plugins/redmine_dashboard/app/views/rdb_dashboard/_taskboard.html.haml:3:in `_plugins_redmine_dashboard_app_views_rdb_dashboard__taskboard_html_haml___1811925154676915027_69918755509220'
plugins/redmine_dashboard/app/views/rdb_dashboard/index.js.erb:1:in `_plugins_redmine_dashboard_app_views_rdb_dashboard_index_js_erb__2264032580956443593_69918755317180'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

Add details about your server:

- OS: CentOS Steam 8
- Appliance: Archive file

**Client information**
Add details about your browser and system here. This is important to debug client problems.

- OS: Microsoft Windows [Version 10.0.19045.2486]
- Browser Opera 
- Version 95.0.4635.25

**Additional context**
The most common installation.

**Ruby|Rails**

```
$ ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

$ rails -v
Rails 5.2.4.2

$ bundle -v
Bundler version 2.4.6

$ bundle info haml
  * haml (6.1.1)
        Summary: An elegant, structured (X)HTML/XML templating engine.
        Homepage: https://haml.info
        Path: /usr/local/rvm/gems/ruby-2.6.6@redmine/gems/haml-6.1.1

```

**Comment by jgraichen** [comment]
Ruby 2.6 and Redmine 4.1.1 are very old. I'll see if I can reproduce the issue, but please be aware that both versions are EOL and not supported by upstream anymore.

**Comment by n0rvik** [comment]
thank you very much

**Comment by jgraichen** [comment]
I was able to run the plugin on Ruby 2.6.6 with Redmine 4.1.1, and it did work:

```
> REDMINE_VERSION=4.1.1 ./redmine server
~/workspace/redmine_dashboard/main/vendor/redmine/4.1.1 ~/workspace/redmine_dashboard/main
+ bundle exec rails server --port 7000
=> Booting Puma
=> Rails 5.2.4.2 application starting in development 
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.12.6 (ruby 2.6.6-p146), codename: Llamas in Pajamas
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:7000
Use Ctrl-C to stop
[..]
```

The dashboard was showing correctly. It seems your environment somehow fails to load the `haml` gem. Is it installed in the correct environment for the Redmine process? Can you try upgrading `rubygems` and/or `bundler` in the environment, e.g. `gem update --system`?

Are some components (e.g. ruby, Redmine, some gems) coming from any system package repository?

**Comment by jgraichen** [comment]
```
  redmine_dashboard              2.10.0
```

Please update to a more recent plugin version.
