### ISSUE TITLE
admin can't see the dashboard but users can

### ISSUE THREAD

**Issue by Raw1mage** [jgraichen/redmine_dashboard#414]
**Describe the bug**

after installing redmine_multiproject_issues plugin, 
the admin can't see the dashboard, but other users are ok.
removing the redmine_multiproject_issues plugin does not fix the error.
looks something in the DB  is permanently changed.

error message shows:

I, [2023-08-18T17:07:35.829483 #1]  INFO -- : Started GET "/projects/ilrdfmis/rdb/taskboard" for 1.34.74.47 at 2023-08-18 17:07:35 +0000
I, [2023-08-18T17:07:35.830747 #1]  INFO -- : Processing by RdbTaskboardController#index as HTML
I, [2023-08-18T17:07:35.830808 #1]  INFO -- :   Parameters: {"id"=>"ilrdfmis"}
I, [2023-08-18T17:07:36.215447 #1]  INFO -- :   Current user: sysadmin (id=1)
I, [2023-08-18T17:07:36.240996 #1]  INFO -- :   Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/index.html.slim within layouts/base (Duration: 3.5ms | Allocations: 1245)
I, [2023-08-18T17:07:36.363278 #1]  INFO -- :   Rendered layout layouts/base.html.erb (Duration: 125.8ms | Allocations: 36747)
I, [2023-08-18T17:07:36.381355 #1]  INFO -- : Completed 200 OK in 550ms (Views: 101.1ms | ActiveRecord: 409.4ms | Allocations: 51665)
I, [2023-08-18T17:07:36.506724 #1]  INFO -- : Started GET "/projects/ilrdfmis/rdb/taskboard?&_=1692378455843" for 1.34.74.47 at 2023-08-18 17:07:36 +0000
I, [2023-08-18T17:07:36.507982 #1]  INFO -- : Processing by RdbTaskboardController#index as JS
I, [2023-08-18T17:07:36.508040 #1]  INFO -- :   Parameters: {"_"=>"1692378455843", "id"=>"ilrdfmis"}
I, [2023-08-18T17:07:36.513594 #1]  INFO -- :   Current user: sysadmin (id=1)
I, [2023-08-18T17:07:36.539470 #1]  INFO -- :   Rendered plugins/redmine_dashboard/app/views/rdb_dashboard/index.js.erb (Duration: 5.4ms | Allocations: 1530)
I, [2023-08-18T17:07:36.539733 #1]  INFO -- : Completed 500 Internal Server Error in 32ms (ActiveRecord: 6.2ms | Allocations: 8368)
F, [2023-08-18T17:07:36.541661 #1] FATAL -- :
ActionView::Template::Error (Couldn't find Tracker with 'id'=6 [WHERE `trackers`.`id` IN (SELECT DISTINCT `trackers`.`id` FROM `trackers` INNER JOIN `projects_trackers` ON `projects_trackers`.`tracker_id` = `trackers`.`id` INNER JOIN `projects` ON `projects`.`id` = `projects_trackers`.`project_id` WHERE `projects`.`id` IN (?, ?, ?, ?, ?))]):
    14:         = link_to val.name, rdb_filter_path(version: val.id)
    15:
    16: .rdb-filter.rdb-async
    17:   - render_rdb_menu :tracker, @board.filters[:tracker].title, icons: true do
    18:     - render_rdb_menu_list [:all] do |val|
    19:       = link_to t("rdb_filter_tracker_#{val}"), rdb_filter_path(tracker: val)
    20:     - render_rdb_menu_list @board.trackers do |val|

plugins/redmine_dashboard/app/models/rdb_tracker_filter.rb:50:in `title'
plugins/redmine_dashboard/app/views/rdb_dashboard/taskboard/_header.html.slim:17
plugins/redmine_dashboard/app/views/rdb_dashboard/_taskboard.html.slim:3
plugins/redmine_dashboard/app/views/rdb_dashboard/index.js.erb:1
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**To Reproduce**

1. install dashboard plugin
2. install multiproject_issues plugin
3. goto /projects/project_name/rdb/taskboard
4. no screen is shown for admin account, but users can see full functions

**Screenshot
![image](https://github.com/jgraichen/redmine_dashboard/assets/40973866/132d40b9-c6ce-41f5-a8e3-ae66493bad71)

```
<Post details (or screenshot) from Redmine > Administration > Information (/admin/info) here>
```

```
<Post Redmine server log here>
```

Add details about your server:

- docker redmine 5.0.5 on synology server

**Client information**
chrome in windows 10

**Comment by Raw1mage** [comment]
kindly looking for a guide to trouble shoot the erroneous tracker id 6

**Comment by Raw1mage** [comment]
l, I just found a quick hack by copying the reset filter request from user account so that the dashboard appears again for the admin account.

https://..../projects/project_name/rdb/taskboard/filter?reset=1
