### ISSUE TITLE
New install have error

### ISSUE THREAD

**Issue by amarkstar** [jgraichen/redmine_dashboard#89]
Hi,

Error thrown in web after i follow below install the redmine on ubuntu:
```
http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_on_Ubuntu_step_by_step
sudo wget https://github.com/jgraichen/redmine_dashboard/archive/v2.6.1.tar.gz
sudo tar zxvf v2.6.1.tar.gz
sudo bundle install
sudo reboot
```
solved after uninstall plugins.

Any one can help for solve issues for install this plugins?
```
uninitialized constant RedmineApp::Application::YAML (NameError)
  /usr/share/redmine/config/application.rb:77:in `<class:Application>'
  /usr/share/redmine/config/application.rb:25:in `<module:RedmineApp>'
  /usr/share/redmine/config/application.rb:24:in `<top (required)>'
  /usr/share/redmine/config/environment.rb:2:in `require'
  /usr/share/redmine/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /usr/lib/ruby/vendor_ruby/ruby/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
  /usr/lib/ruby/vendor_ruby/ruby/1.9.1/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:112:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'
```
Activated Ruby gems
```
bundler => 1.9.4
rake => 10.4.2
i18n => 0.7.0
json => 1.8.2
minitest => 5.6.0
thread_safe => 0.3.5
tzinfo => 1.2.2
activesupport => 4.2.1
builder => 3.2.2
erubis => 2.7.0
mini_portile => 0.6.2
nokogiri => 1.6.6.2
rails-deprecated_sanitizer => 1.0.3
rails-dom-testing => 1.0.6
loofah => 2.0.1
rails-html-sanitizer => 1.0.2
actionview => 4.2.1
rack => 1.6.0
rack-test => 0.6.3
actionpack => 4.2.1
activemodel => 4.2.1
mime-types => 2.5
xpath => 2.0.0
capybara => 2.4.4
hitimes => 1.2.2
timers => 4.0.1
celluloid => 0.16.0
cliver => 0.3.2
coderay => 1.1.0
database_cleaner => 1.4.1
diff-lcs => 1.2.5
multipart-post => 1.2.0
faraday => 0.8.9
faraday_middleware => 0.9.1
ffi => 1.9.8
formatador => 0.2.5
rspec-core => 2.99.2
rspec-expectations => 2.99.2
rspec-mocks => 2.99.3
rspec => 2.99.0
ruby-progressbar => 1.7.5
fuubar => 1.3.3
rb-fsevent => 0.9.4
rb-inotify => 0.9.5
listen => 2.10.0
lumberjack => 1.0.9
nenv => 0.2.0
shellany => 0.0.1
notiffany => 0.0.6
method_source => 0.8.2
slop => 3.6.0
pry => 0.10.1
thor => 0.19.1
guard => 2.12.5
guard-compat => 1.2.1
guard-rspec => 4.5.0
tilt => 2.0.1
haml => 4.0.6
hashie => 1.2.0
inifile => 3.0.0
multi_json => 1.11.0
websocket-extensions => 0.1.2
websocket-driver => 0.5.4
poltergeist => 1.6.0
power_assert => 0.2.3
railties => 4.2.1
rspec-collection_matchers => 1.1.2
rspec-rails => 2.99.0
test-unit => 3.0.9
transifex-ruby-fork-jg => 0.1.0
```

**Comment by jgraichen** [comment]
Please see [Redmine Wiki](http://www.redmine.org/projects/redmine/wiki/Plugins ) on how to install plug-ins.

Also make sure the plugin is extracted to `plugins/redmine_dashboard`. Try to use an archive from the [release page](https://github.com/jgraichen/redmine_dashboard/releases/tag/v2.6.1) and extract it in `plugins`. Then run `bundle install --without development test` in the Redmine directory.

If you have installed Redmine using `apt-get` or `aptitude` you can also install this plugin via `apt-get` or `aptitude` using [the PPA](https://launchpad.net/~jgraichen/+archive/ubuntu/redmine-dashboard/).
